/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-04-07 09:08:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.chaApp.models.*;

public final class listeMessages_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/views/header.jsp", Long.valueOf(1679008650912L));
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1679008435812L));
    _jspx_dependants.put("jar:file:/D:/projet/WebChat/src/main/webapp/wtpwebapps/WebChat/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602870372000L));
    _jspx_dependants.put("/./WEB-INF/includes/sidebar.jsp", Long.valueOf(1680847070195L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("com.chaApp.models");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "Les JSPs ne permettent que GET, POST ou HEAD. Jasper permet aussi OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" ");
      out.write("\r\n");
      out.write("<!-- <!DOCTYPE html>\r\n");
      out.write("<html> -->\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>ChatApp</title>\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD\" crossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css\"/>\r\n");
      out.write("<link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(" *{\r\n");
      out.write("margin:0;\r\n");
      out.write("padding:0;\r\n");
      out.write("outline:none;\r\n");
      out.write("border:none;\r\n");
      out.write("text-decoration:none;\r\n");
      out.write("box-sizing:border-box;\r\n");
      out.write("font-family:sans-serif;\r\n");
      out.write("\r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write("body{\r\n");
      out.write("   background-color: #fbab7e; \r\n");
      out.write(" background-image: linear-gradient(62deg, #fbab7e 0%, #d90647 100%);\r\n");
      out.write("   height: 300vh;\r\n");
      out.write("  width: 100vw; } \r\n");
      out.write("nav{\r\n");
      out.write("position:absolute;\r\n");
      out.write("top:0;\r\n");
      out.write("bottom:0;\r\n");
      out.write("height: 300vh;\r\n");
      out.write("left:0;\r\n");
      out.write("background:#fff;\r\n");
      out.write("width:110px;\r\n");
      out.write("overflow:hidden;\r\n");
      out.write("transition:width 0.2s linear;\r\n");
      out.write("box-shadow:0 20px 35px rgba(0,0,0,0.1);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logo{\r\n");
      out.write("text-align:center;\r\n");
      out.write("display:flex;\r\n");
      out.write("transition:all 0.5s ease;\r\n");
      out.write("margin:10px 0 0 ;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("ul{\r\n");
      out.write(" list-style-type: none;\r\n");
      out.write("}\r\n");
      out.write(".logo img{\r\n");
      out.write("width:75px;\r\n");
      out.write("height:75px;\r\n");
      out.write("border-radius:50%;\r\n");
      out.write("}\r\n");
      out.write(".logo span{\r\n");
      out.write("font-weight:bold;\r\n");
      out.write("padding-left:15px;\r\n");
      out.write("font-size:18px;\r\n");
      out.write("text-transform:uppercase;\r\n");
      out.write("}\r\n");
      out.write("a{\r\n");
      out.write("position:relative;\r\n");
      out.write("color:rgb(85,83,83);\r\n");
      out.write("font-size:14px;\r\n");
      out.write("display:table;\r\n");
      out.write("width:300px;\r\n");
      out.write("padding:10px;\r\n");
      out.write("text-decoration:none;\r\n");
      out.write("}\r\n");
      out.write(".fas{\r\n");
      out.write("position:relative;\r\n");
      out.write("width:70px;\r\n");
      out.write("height:40px;\r\n");
      out.write("top:14px;\r\n");
      out.write("font-size:20px;\r\n");
      out.write("text-align:center;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".nav-item{\r\n");
      out.write("position:relative;\r\n");
      out.write("top:12px;\r\n");
      out.write("margin-left:10px;\r\n");
      out.write("}\r\n");
      out.write("a:hover{\r\n");
      out.write("backgound:#eee;\r\n");
      out.write("text-decoration:none;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("nav:hover{\r\n");
      out.write("text-decoration:none;\r\n");
      out.write("width:280px;\r\n");
      out.write("transition:all 0.5s ease;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".logout{\r\n");
      out.write("position:absolute;\r\n");
      out.write("bottom:0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<!-- <body> -->\r\n");
      out.write("	<nav>\r\n");
      out.write("		<ul>\r\n");
      out.write("			<li>\r\n");
      out.write("				\r\n");
      out.write("				<a href=\"#\" class=\"logo\">\r\n");
      out.write("					<img src=\"./photos/logo.png\" alt=\"\" class=\"logo_img\">\r\n");
      out.write("					<span class=\"nav-item\">ChatApp</span>\r\n");
      out.write("				</a>\r\n");
      out.write("			</li>\r\n");
      out.write("			<li><a href=\"\" >\r\n");
      out.write("				<i class=\"fas fa-home\" style=\"color: #000000;\"></i>\r\n");
      out.write("				<span class=\"nav-item\" style=\"color: #000000;\">Home </span>\r\n");
      out.write("			</a></li>\r\n");
      out.write("			<li><a href=\"Show\" >\r\n");
      out.write("				<i class=\"fas fa-user\" style=\"color: #000000;\"></i>\r\n");
      out.write("				<span class=\"nav-item\" style=\"color: #000000;\">Profile </span>\r\n");
      out.write("			</a></li>\r\n");
      out.write("			<li><a href=\"Ajouter.jsp\" >\r\n");
      out.write("				<i class=\"fas fa-wallet\" style=\"color: #000000;\"></i>\r\n");
      out.write("				<span class=\"nav-item\" style=\"color: #000000;\">Add contact </span>\r\n");
      out.write("			</a></li>\r\n");
      out.write("			<li><a href=\"show_invit.jsp\" >\r\n");
      out.write("				<i class=\"fas fa-chart-bar\" style=\"color: #000000;\"></i>\r\n");
      out.write("				<span class=\"nav-item\" style=\"color: #000000;\">display invitations </span>\r\n");
      out.write("			</a></li>\r\n");
      out.write("			<li><a href=\"FetchData\" >\r\n");
      out.write("				<i class=\"fas fa-tasks\" style=\"color: #000000;\"></i>\r\n");
      out.write("				<span class=\"nav-item\" style=\"color: #000000;\">Display contact </span>\r\n");
      out.write("				\r\n");
      out.write("			\r\n");
      out.write("			</a></li>\r\n");
      out.write("			<li><a href=\"ListeMessages\" >\r\n");
      out.write("				<i class=\"fas fa-envelope\" style=\"color: #000000;\"></i>\r\n");
      out.write("				<span class=\"nav-item\" style=\"color: #000000;\">Liste Discussions </span>\r\n");
      out.write("			</a></li>\r\n");
      out.write("			\r\n");
      out.write("			<!-- <li><a href=\"#\" >\r\n");
      out.write("				<i class=\"fas fa-question-circle\" style=\"color: #000000;\"></i>\r\n");
      out.write("				<span class=\"nav-item\" style=\"color: #000000;\">Help </span>\r\n");
      out.write("			</a></li> -->\r\n");
      out.write("			\r\n");
      out.write("						\r\n");
      out.write("			<li><a  >\r\n");
      out.write("				<i  class=\"fas fa-sign-out\" class=\"logout\" style=\"color: #000000;\"></i>\r\n");
      out.write("			\r\n");
      out.write("				<button type=\"button\" class=\"nav-item\" data-toggle=\"modal\" data-target=\"#e\">\r\n");
      out.write("				 Se déconnecter\r\n");
      out.write("				</button>\r\n");
      out.write("<div class=\"modal fade\" id=\"e\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"ex\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("    <div class=\"modal-content\" >\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"ex\">Déconnexion</h5>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        <p>Si vous vous déconnecter, tous vos discussions actuelles seront supprimés</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Annuler</button>\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-primary\"  onclick=\"deconnecter()\">Se déconnecter</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("				</a>\r\n");
      out.write("				\r\n");
      out.write("			</li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		</ul>\r\n");
      out.write("	</nav>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function deconnecter(){\r\n");
      out.write("	\r\n");
      out.write("	 window.location.href = 'http://localhost:8081/WebChat/Login';\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- </body>\r\n");
      out.write("</html> -->");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Chat App</title>\r\n");
      out.write("    \r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css\" integrity=\"sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("body,\r\n");
      out.write("html {\r\n");
      out.write("/* 	height: 100%;\r\n");
      out.write(" */\r\n");
      out.write("  width: 125vw;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".chat {\r\n");
      out.write("	margin-top: auto;\r\n");
      out.write("	margin-bottom: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card {\r\n");
      out.write("	margin: 40;\r\n");
      out.write("	height: 500px;\r\n");
      out.write("	border-radius: 15px !important;\r\n");
      out.write("	background-color: rgba(0, 0, 0, 0.4) !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contacts_body {\r\n");
      out.write("	padding: 0.75rem 0 !important;\r\n");
      out.write("	overflow-y: auto;\r\n");
      out.write("	white-space: nowrap;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".msg_card_body {\r\n");
      out.write("	overflow-y: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-header {\r\n");
      out.write("	border-radius: 15px 15px 0 0 !important;\r\n");
      out.write("	border-bottom: 0 !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-footer {\r\n");
      out.write("	border-radius: 0 0 15px 15px !important;\r\n");
      out.write("	border-top: 0 !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("	align-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search {\r\n");
      out.write("	border-radius: 15px 0 0 15px !important;\r\n");
      out.write("	background-color: rgba(0, 0, 0, 0.3) !important;\r\n");
      out.write("	border: 0 !important;\r\n");
      out.write("	color: white !important;\r\n");
      out.write("	height:48px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search:focus {\r\n");
      out.write("	box-shadow: none !important;\r\n");
      out.write("	outline: 0px !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".type_msg {\r\n");
      out.write("	background-color: rgba(0, 0, 0, 0.3) !important;\r\n");
      out.write("	border: 0 !important;\r\n");
      out.write("	color: white !important;\r\n");
      out.write("	height: 60px !important;\r\n");
      out.write("	overflow-y: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".type_msg:focus {\r\n");
      out.write("	box-shadow: none !important;\r\n");
      out.write("	outline: 0px !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* .attach_btn {\r\n");
      out.write("	border-radius: 15px 0 0 15px !important;\r\n");
      out.write("	background-color: rgba(0, 0, 0, 0.3) !important;\r\n");
      out.write("	border: 0 !important;\r\n");
      out.write("	color: white !important;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("} */\r\n");
      out.write("\r\n");
      out.write(".send_btn {\r\n");
      out.write("	border-radius: 0 15px 15px 0 !important;\r\n");
      out.write("	background-color: rgba(0, 0, 0, 0.3) !important;\r\n");
      out.write("	border: 0 !important;\r\n");
      out.write("	color: white !important;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(" .search_btn {\r\n");
      out.write("	border-radius: 0 15px 15px 0 !important;\r\n");
      out.write("	background-color: rgba(0, 0, 0, 0.3) !important;\r\n");
      out.write("	border: 0 !important;\r\n");
      out.write("	color: white !important;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write(".contacts {\r\n");
      out.write("	list-style: none;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contacts li {\r\n");
      out.write("	width: 100% !important;\r\n");
      out.write("	padding: 5px 10px;\r\n");
      out.write("	margin-bottom: 15px !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".active {\r\n");
      out.write("	background-color: rgba(0, 0, 0, 0.3);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".user_img {\r\n");
      out.write("	height: 60px;\r\n");
      out.write("	width: 60px;\r\n");
      out.write("	border: 1.5px solid #f5f6fa;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".user_img_msg {\r\n");
      out.write("	height: 40px;\r\n");
      out.write("	width: 40px;\r\n");
      out.write("	border: 1.5px solid #f5f6fa;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".img_cont {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	height: 70px;\r\n");
      out.write("	width: 70px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".img_cont_msg {\r\n");
      out.write("	height: 40px;\r\n");
      out.write("	width: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".online_icon {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	height: 15px;\r\n");
      out.write("	width: 15px;\r\n");
      out.write("	background-color: #4cd137;\r\n");
      out.write("	border-radius: 50%;\r\n");
      out.write("	bottom: 13px;\r\n");
      out.write("	right: 13px;\r\n");
      out.write("	border: 1.5px solid white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".offline {\r\n");
      out.write("	background-color: #c23616 !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".user_info {\r\n");
      out.write("	margin-top: auto;\r\n");
      out.write("	margin-bottom: auto;\r\n");
      out.write("	margin-left: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".user_info span {\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".user_info p {\r\n");
      out.write("	font-size: 10px;\r\n");
      out.write("	color: rgba(255, 255, 255, 0.6);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("./* msg_cotainer {\r\n");
      out.write("	margin-top: auto;\r\n");
      out.write("	margin-bottom: auto;\r\n");
      out.write("	margin-left: 10px;\r\n");
      out.write("	border-radius: 25px;\r\n");
      out.write("	background-color: #82ccdd;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".msg_cotainer_send {\r\n");
      out.write("	margin-top: auto;\r\n");
      out.write("	margin-bottom: auto;\r\n");
      out.write("	margin-right: 10px;\r\n");
      out.write("	border-radius: 25px;\r\n");
      out.write("	background-color: #78e08f;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	position: relative;\r\n");
      out.write("} */\r\n");
      out.write("\r\n");
      out.write("/* .msg_time {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	bottom: -15px;\r\n");
      out.write("	color: rgba(255, 255, 255, 0.5);\r\n");
      out.write("	font-size: 10px;\r\n");
      out.write("} */\r\n");
      out.write("\r\n");
      out.write("/* .msg_time_send {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	right: 0;\r\n");
      out.write("	bottom: -15px;\r\n");
      out.write("	color: rgba(255, 255, 255, 0.5);\r\n");
      out.write("	font-size: 10px;\r\n");
      out.write("} */\r\n");
      out.write("\r\n");
      out.write(".msg_head {\r\n");
      out.write("	position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* width */\r\n");
      out.write("\r\n");
      out.write(" ::-webkit-scrollbar {\r\n");
      out.write("	width: 10px;\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("/* Track */\r\n");
      out.write("\r\n");
      out.write("::-webkit-scrollbar-track {\r\n");
      out.write("	background: #f1f1f1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* Handle */\r\n");
      out.write("\r\n");
      out.write("::-webkit-scrollbar-thumb {\r\n");
      out.write("	background: #888;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* Handle on hover */\r\n");
      out.write("\r\n");
      out.write("::-webkit-scrollbar-thumb:hover {\r\n");
      out.write("	background: #555;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media(max-width: 576px) {\r\n");
      out.write("	.contacts_card {\r\n");
      out.write("		margin-bottom: 15px !important;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".message-count {\r\n");
      out.write("\r\n");
      out.write("background-color: #25d366;\r\n");
      out.write("\r\n");
      out.write("color: #fff;\r\n");
      out.write("\r\n");
      out.write("border-radius: 50%;\r\n");
      out.write("\r\n");
      out.write("font-size: 12px;\r\n");
      out.write("\r\n");
      out.write("width: 20px;\r\n");
      out.write("\r\n");
      out.write("height: 20px;\r\n");
      out.write("\r\n");
      out.write("display: flex;\r\n");
      out.write("\r\n");
      out.write("align-items: center;\r\n");
      out.write("\r\n");
      out.write("justify-content: center;\r\n");
      out.write("\r\n");
      out.write("margin-bottom: 5px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".message-time {\r\n");
      out.write("\r\n");
      out.write("font-size: 12px;\r\n");
      out.write("\r\n");
      out.write("color: #999;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Chat App</title>\r\n");
      out.write("    \r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css\" integrity=\"sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid h-50\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"row justify-content-center h-100 vh-70\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"col-md-8 col-xl-7 justify-content-center\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"card mb-sm-3 mb-md-0 contacts_card\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"card-header\">\r\n");
      out.write("						<div class=\"input-group\">\r\n");
      out.write("							<input id=\"myInput\" type=\"text\" placeholder=\"Search...\" name=\"\" class=\"form-control search\">\r\n");
      out.write("							<div class=\"input-group-prepend\">\r\n");
      out.write("								<span class=\"input-group-text search_btn\"><i class=\"fas fa-search\"></i></span>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div> \r\n");
      out.write("\r\n");
      out.write("<div class=\"card-body contacts_body\">\r\n");
      out.write("\r\n");
      out.write("<ui class=\"contacts\" id=\"contacts\">\r\n");
      out.write("\r\n");
      //  c:forEach
      org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
      boolean _jspx_th_c_005fforEach_005f0_reused = false;
      try {
        _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fforEach_005f0.setParent(null);
        // /WEB-INF/views/listeMessages.jsp(327,0) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/listeMessages.jsp(327,0) '${derniersMessages}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${derniersMessages}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
        // /WEB-INF/views/listeMessages.jsp(327,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setVar("message");
        int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
        try {
          int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
          if (_jspx_eval_c_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("\r\n");
              out.write("\r\n");
              out.write("<li class=\"active \">\r\n");
              out.write("\r\n");
              out.write("<div class=\"message row justify-content-between align-items-center\" id=\"");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message.id_emetteur}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("\" >\r\n");
              out.write("\r\n");
              if (_jspx_meth_c_005fset_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
                return;
              out.write("\r\n");
              out.write("\r\n");
              if (_jspx_meth_c_005fset_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
                return;
              out.write("\r\n");
              out.write("\r\n");


int id_emet=(Integer)pageContext.getAttribute("id_emet");

int id_rec=(Integer)pageContext.getAttribute("id_rec");

Utilisateur user = DAOUser.recupererUser(id_emet);


              out.write("\r\n");
              out.write("\r\n");
              out.write("<div class=\"col-7 d-flex bd-highlight\">\r\n");
              out.write("\r\n");
              out.write("<div class=\"img_cont\">\r\n");
              out.write("\r\n");
              out.write("<!-- image de profil -->\r\n");
              out.write("\r\n");
              out.write("  <img src=\"././");
              out.print( user.getPhoto() );
              out.write("\" class=\"rounded-circle user_img\"/>\r\n");
              out.write("\r\n");
              out.write("</div>\r\n");
              out.write("\r\n");
              out.write("<div class=\"user_info\">\r\n");
              out.write("\r\n");
              out.write("<!-- nom -->\r\n");
              out.write("\r\n");
              out.write("<span>");
              out.print( user.getNom() );
              out.write("</span>\r\n");
              out.write("\r\n");
              out.write("<p id=\"m");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message.id_emetteur}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("\" class=\"fz-2\"> <strong>");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message.contenu}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("</strong></p>\r\n");
              out.write("\r\n");
              out.write("</div>\r\n");
              out.write("\r\n");
              out.write("</div>\r\n");
              out.write("\r\n");
              out.write("<div class=\"col-3 message-details\">\r\n");
              out.write("\r\n");
              out.write("<div class=\"message-count ml-5\" id=\"count");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message.id_emetteur}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write('"');
              out.write('>');
              out.write(' ');
 out.println(new MessageRecus().nombreMessages(id_rec,id_emet)); 
              out.write(" </div>\r\n");
              out.write("\r\n");
              out.write("<div class=\"message-time \" id=\"d");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message.id_emetteur}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write('"');
              out.write('>');
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message.date_envoi}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("</div>\r\n");
              out.write("\r\n");
              out.write("</div>\r\n");
              out.write("</div>\r\n");
              out.write("</li>\r\n");
              out.write("\r\n");
              int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
              if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_c_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
        } finally {
          _jspx_th_c_005fforEach_005f0.doFinally();
        }
        _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
        _jspx_th_c_005fforEach_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
      }
      out.write(" </ui> </div></div></div></div></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<p class=\"d-none\" id=\"id\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var items = document.querySelectorAll(\".active\");\r\n");
      out.write("\r\n");
      out.write("var input = document.querySelector(\"#myInput\");\r\n");
      out.write("\r\n");
      out.write("input.addEventListener(\"keyup\", function() {\r\n");
      out.write("  var filter = input.value.toUpperCase();\r\n");
      out.write("\r\n");
      out.write("  for (var i = 0; i < items.length; i++) {\r\n");
      out.write("    var item = items[i];\r\n");
      out.write("    var text = item.textContent.toUpperCase();\r\n");
      out.write("\r\n");
      out.write("    if (text.indexOf(filter) > -1) {\r\n");
      out.write("      item.style.display = \"\";\r\n");
      out.write("    } else {\r\n");
      out.write("      item.style.display = \"none\";\r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("//\r\n");
      out.write("\r\n");
      out.write("let id=document.getElementById(\"id\").textContent;\r\n");
      out.write("\r\n");
      out.write("const queryString = window.location.search;\r\n");
      out.write("\r\n");
      out.write("const urlParams = new URLSearchParams(queryString);\r\n");
      out.write("\r\n");
      out.write("let socket = new WebSocket(\"ws://localhost:8081/WebChat/ServerEndPoint3?userID=\"+id);\r\n");
      out.write("\r\n");
      out.write("socket.onopen = function(e) {\r\n");
      out.write("\r\n");
      out.write("console.log(\"[open] Connection established liste messages\");\r\n");
      out.write("\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("socket.onmessage=function(event){\r\n");
      out.write("\r\n");
      out.write("console.log(\"arriev!!!\");\r\n");
      out.write("\r\n");
      out.write("const Data = event.data;\r\n");
      out.write("\r\n");
      out.write("var objectR = JSON.parse(Data);\r\n");
      out.write("//var formData = new FormData();\r\n");
      out.write("//formData.append(\"contenu\",objectR.content);\r\n");
      out.write("//console.log('Hiii ajax '+formData);\r\n");
      out.write("var data = \"contenu=\" + encodeURIComponent(objectR.content);\r\n");
      out.write("var xhr = new XMLHttpRequest();\r\n");
      out.write(" xhr.open('POST', 'http://localhost:8081/WebChat/AjaxCall3',true);\r\n");
      out.write(" xhr.setRequestHeader(\"Content-type\", \"application/x-www-form-urlencoded\");\r\n");
      out.write(" xhr.onload = function() {\r\n");
      out.write("   if (xhr.status === 200) {\r\n");
      out.write("	  \r\n");
      out.write("	   valeur = xhr.responseText;\r\n");
      out.write("       console.log('hellooooooooooooooooooo:', xhr.status);\r\n");
      out.write("       var discuss = document.querySelectorAll(\".message\");\r\n");
      out.write("       var found=0;\r\n");
      out.write("       for (var i = 0; i < discuss.length; i++) {\r\n");
      out.write("\r\n");
      out.write("                 if(discuss[i].id==objectR.emet){\r\n");
      out.write("\r\n");
      out.write("                   console.log(\" found hi\");\r\n");
      out.write("\r\n");
      out.write("                   var count = document.getElementById(\"count\"+objectR.emet).textContent;\r\n");
      out.write("\r\n");
      out.write("                   document.getElementById(\"count\"+objectR.emet).textContent=parseInt(count)+1;\r\n");
      out.write("\r\n");
      out.write("                   var contenu = document.getElementById(\"m\"+objectR.emet).textContent;\r\n");
      out.write("\r\n");
      out.write("                   document.getElementById(\"m\"+objectR.emet).textContent=valeur;\r\n");
      out.write("\r\n");
      out.write("                   var count = document.getElementById(\"d\"+objectR.emet).textContent;\r\n");
      out.write("\r\n");
      out.write("                   document.getElementById(\"d\"+objectR.emet).textContent=objectR.date;\r\n");
      out.write("\r\n");
      out.write("                   console.log(count);\r\n");
      out.write("                   found=1;\r\n");
      out.write("                   break;\r\n");
      out.write("                  }\r\n");
      out.write("\r\n");
      out.write("       };\r\n");
      out.write("       if(!found){\r\n");
      out.write("       	var discussion = document.createElement('li');\r\n");
      out.write("       	discussion.innerHTML = '<div class=\"message row justify-content-between align-items-center\" id=\"'+objectR.emet+'\" ><div class=\"col-7 d-flex bd-highlight\"><div class=\"img_cont\"><img src=\"././'+objectR.photo_rec+'\" class=\"rounded-circle user_img\"/></div><div class=\"user_info\"><span>'+objectR.nom_rec+'</span><p id=\"m'+objectR.emet+'\"> <strong>'+valeur+'</strong></p></div></div><div class=\"col-3 message-details\"><div class=\"message-count ml-5\" id=\"count'+objectR.emet+'\">1</div><div class=\"message-time\" id=\"d'+objectR.emet+'\">'+objectR.date+'</div></div></div></li>';\r\n");
      out.write("       	 discussion.classList.add('active');\r\n");
      out.write("       	 document.getElementById(\"contacts\").appendChild( discussion);\r\n");
      out.write("       }\r\n");
      out.write("	   \r\n");
      out.write("   } else {\r\n");
      out.write("	   console.log('Error:', xhr.status);\r\n");
      out.write("   }  \r\n");
      out.write(" }\r\n");
      out.write(" xhr.send(data); \r\n");
      out.write("\r\n");
      out.write("console.log(objectR);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// CLOSE\r\n");
      out.write("\r\n");
      out.write("socket.onclose=function(){\r\n");
      out.write("\r\n");
      out.write("console.log(\"cloosed liste disc!\");\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// ERROR\r\n");
      out.write("\r\n");
      out.write("socket.onerror = function(error) {\r\n");
      out.write("\r\n");
      out.write("console.log(error);\r\n");
      out.write("\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("document.addEventListener(\"DOMContentLoaded\", function() {\r\n");
      out.write("\r\n");
      out.write("var myDivs = document.querySelectorAll(\".message\");\r\n");
      out.write("\r\n");
      out.write("for (var i = 0; i < myDivs.length; i++) {\r\n");
      out.write("\r\n");
      out.write("myDivs[i].addEventListener(\"click\", function() {\r\n");
      out.write("\r\n");
      out.write("var id = this.id;\r\n");
      out.write("\r\n");
      out.write("var url = \"addMessage?id=\" + encodeURIComponent(id);\r\n");
      out.write("\r\n");
      out.write("window.location.href = url;\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("	\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/listeMessages.jsp(333,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("id_emet");
      // /WEB-INF/views/listeMessages.jsp(333,0) name = value type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/listeMessages.jsp(333,0) '${message.id_emetteur}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${message.id_emetteur}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/listeMessages.jsp(335,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("id_rec");
      // /WEB-INF/views/listeMessages.jsp(335,0) name = value type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/listeMessages.jsp(335,0) '${message.id_recepteur}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${message.id_recepteur}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }
}
